version: "3"
services:
  chalkboard:
    container_name: chalkboard
    image: hrl3733/chalkboad
    restart: always
    build: .
    command: npm start
    ports:
      - "3733:3733"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
